name: styled
channels:
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pytorch=1.10.2
  - torchvision=0.11.3
  - cudatoolkit=11.3
  - matplotlib
  - ninja
  - scikit-image
  - scikit-learn
  - pip:
    - clean-fid==0.1.21
    - opencv-python-headless
    - packaging
    - lmdb
    - lpips
    - torchinfo
    - huggingface_hub
